### ISSUE TITLE
Compilation issue for pylime

### ISSUE THREAD

**Issue by yaolun** [lime-rt/lime#251]
I have encountered several issues when trying to compile the python version of lime (pylime).  The machine I am using is running RedHat Enterprise 6.6.  All of them were solved by adding paths for CPPFLAGS or LIBS, except for one.

I got the following error messages when executing `make python`

> src/pymain.o:(.bss+0x4): multiple definition of `fixRandomSeeds'
src/run.o:(.bss+0x4): first defined here

It seems like the `fixRandomSeeds` is defined in two places, causing the error.

---

Here are some other issues I had but managed to figure out.

- Need to include the library for python and cfitsio.   Error messages like `src/lime.h:14:20: error: Python.h: No such file or directory`
  - The compiler can't find the python library if a personal build of python is used.  In my case, I am using Anaconda, so I have to add `-I${HOME}/anaconda/include/python2.7` to `CPPFLAGS`.
  - For reasons I don't know, I have to manually include the path to `cfitsio` to the `CPPFLAGS`.

- Then I started to get error messages like `aux.c:(.text+0x725): undefined reference to 'Py_Finalize'`, and many other python related errors.
  - To fix these errors, the following paths need to be added to `LIBS` (this also depends on my Anaconda python distribution): `-L${HOME}/anaconda/lib/python2.7/config` and `-lpython2.7`.

- Finally, I got these error messages:

> posixmodule.c:(.text+0x27af): undefined reference to 'forkpty'
posixmodule.c:(.text+0x4496): undefined reference to 'openpty'
  - It requires adding `-lutil` to `LIBS`.

I also have some comments when working on this issue.  First, the documentation says that the `pylime` is supported in version 1.9.  However, the only place I can find the version number is when running the regular version of `lime`, which shows version 1.8.  This is the `lime` freshly cloned from Github at this moment.  Also it may be useful to state that `lime` currently supporting python 2.7 (at least this is what I understand), especially we are now on the verge of people starting to migrate to python 3.

**Comment by allegroLeiden** [comment]
Hi, sorry you had to wait so long for a reply - I have been pretty busy preparing for the next release, and nobody else does much work on LIME these days.

I'm guessing you're using the master branch, since that is the only one that includes the python interface. I've actually done quite a bit of work since then, mainly cleaning up things rather than adding new functionality, in preparation for the official release of this stuff as 1.9. The very latest code you will find in the 'casa' branch of my own fork of lime. Can I ask you to download that, configure it, do 'make pylime' (I changed the name of the make target), and see if it compiles?

We currently store the version number as a macro in lime.h.

I don't know if the python interface will work under python 3. This is on the todo list to test. (It's kind of a long list.)

**Comment by yaolun** [comment]
Hi, sorry for the late respond.

I got the branch from your fork (I couldn't find the "casa" branch somehow, so I just used the master in your fork.).  I managed to compile the "pylime" after few tweaks in the Makefile, such as adding the path of my python distribution for `CPPFLAGS` and adding the path of my python config for `LIBS`.  However, I got an `ImportError` when trying to run the example.

> ImportError: No module named par_classes

I also found that there is no `par_classes.pyc` under `lime/python/` indicating that `par_classes` is not compiled.  I suspect that some path went wrong so the code cannot find the `par_classes` correctly.

Thanks.

**Comment by allegroLeiden** [comment]
Hi @yaolun . Yes, events have moved on, last week I merged my casa branch into lime-rt and issued it as release 1.9! However my master branch should be (at present) almost identical.

Did you run the setup script pyrc.sh (pyrc.csh for c-shell)? Actually all that does is add the necessary directories to PYTHONPATH so pylime will be able find par_classes.py. You can also just do that by hand.

**Comment by yaolun** [comment]
@allegroLeiden, it works!  I didn't realize that I have to source the `pyrc.sh` from the `README.MD`.  Thanks for helping out.

**Comment by allegroLeiden** [comment]
I'm still a bit curious that you had to hack the Makefile. The configure script is supposed to load all the necessary python stuff into variables PYCCFLAGS and PYLDFLAGS which are then read from Makefile.defs. It gets them by running python-config and should fail if that script is not present. Did this not work, and if not, exactly how did it fail? Could you maybe send me the Makefile and Makefile.defs which you succeeded in building pylime with?

**Comment by yaolun** [comment]
I have to add two things in the `Makefile` manually to make it work.  One is for the `Cfitsio`.  Maybe I installed it incorrectly so that the `Makefile` couldn't find it.  The other one is the python library for the `LIBS`.  If I don't have this one, I would have the following error.
> /usr/bin/ld: cannot find -lpython2.7

Here are the `Makefile` and `Makefile.defs`.
[pylime_makefile.zip](https://github.com/lime-rt/lime/files/1439512/pylime_makefile.zip)

**Comment by allegroLeiden** [comment]
@yaolun you sent me Makefile.srcs not Makefile.defs.

Ok I can see in the Makefile how you have the cfitsio headers in a nonstandard place. I'll have a think about how to deal with that... I've been reluctant to go down the full autoconf route, and I don't really want to have the config script do a big find on the user's whole file system.

**Comment by allegroLeiden** [comment]
Some of these problems at least should be fixed in the current master track. It would be useful if you could get hold of this and see if it sets up any easier for you.

**Comment by allegroLeiden** [comment]
@yaolun can I close this?

**Comment by yaolun** [comment]
I tried to get a fresh repo and compiled from it.  However, I still encounter problems with it.  I would post the error here, but the machine I am using is having other problems right now.  I will test it again soon.
